import { supportedLanguages } from 'reporthar';

// Vendored from datenanfragen/data.
// TODO: In the future, it would be nice to have a package that exports these.
const dpaData = {
    atdsb: {
        slug: 'atdsb',
        'relevant-countries': ['at'],
        name: 'Österreichische Datenschutzbehörde',
        address: 'Barichgasse 40-42\n1030 Wien\nÖsterreich',
        phone: '+43 1 52 152 0',
        email: 'dsb@dsb.gv.at',
        webform:
            'https://www.formularservice.gv.at/site/fsrv/user/formular.aspx?pid=5a37966ab26c4489adc20dc53162fa4d&pn=Bf10e1134f601464e9b3835170de668bd',
        web: 'https://www.dsb.gv.at/',
        sources: [
            'https://www.dsb.gv.at/kontakt',
            'https://www.dsb.gv.at/Eingabeformular-online/Eingabeformular-online.html',
        ],
        'complaint-language': 'de',
    },
    beapd: {
        slug: 'beapd',
        'relevant-countries': ['be'],
        name: 'Autorité de protection des données de Belgique, Gegevensbeschermingsautoriteit van België',
        address: 'Drukpersstraat 35\n1000 Brussels\nBelgium',
        phone: '+32 2 274 48 00',
        fax: '+32 2 274 48 35',
        email: 'contact@apd-gba.be',
        webform: 'https://www.dataprotectionauthority.be/citizen/actions/lodge-a-complaint',
        web: 'https://www.dataprotectionauthority.be/',
        sources: ['https://www.gegevensbeschermingsautoriteit.be/burger/acties/contact'],
    },
    bgcpdp: {
        slug: 'bgcpdp',
        'relevant-countries': ['bg'],
        name: 'Commission for Personal Data Protection Bulgaria',
        address: '2 Prof. Tsvetan Lazarov Blvd.\nSofia 1592\nBulgaria',
        phone: '+359 2 915 3519',
        fax: '+359 2 915 3525',
        email: 'kzld@cpdp.bg',
        web: 'https://www.cpdp.bg',
        sources: ['https://www.cpdp.bg/en/index.php?p=pages&aid=56', 'https://www.cpdp.bg/en/index.php?p=pages&aid=5'],
        'complaint-language': 'bg',
        comments: ['Complaints by email must be signed with a qualified electronic signature (QES).'],
    },
    chedoeb: {
        slug: 'chedoeb',
        'relevant-countries': ['ch'],
        name: 'EDÖB – Eidgenössischer Datenschutz- und Öffentlichkeitsbeauftragter',
        address: 'Feldeggweg 1\n3003 Bern\nSchweiz',
        phone: '+41 58 462 43 95',
        fax: '+41 58 465 99 96',
        webform: 'https://www.edoeb.admin.ch/edoeb/de/home/der-edoeb/kontakt/kontaktformular.html',
        web: 'https://www.edoeb.admin.ch',
        sources: [
            'https://www.edoeb.admin.ch/edoeb/de/home/der-edoeb/kontakt.html',
            'https://www.edoeb.admin.ch/edoeb/de/home/der-edoeb/kontakt/adresse.html',
        ],
        'complaint-language': 'de',
    },
    cydp: {
        slug: 'cydp',
        'relevant-countries': ['cy'],
        name: 'Γραφείο Επιτρόπου Δεδομένων Προσωπικού Χαρακτήρα (Personal Data Commissioner of Cyprus)',
        address: 'Τ.Θ. 23378\n1682 Λευκωσία (Nicosia)\nCyprus',
        phone: '+357 22 818456',
        fax: '+357 22 304565',
        email: 'commissioner@dataprotection.gov.cy',
        webform:
            'https://www.dataprotection.gov.cy/dataprotection/dataprotection.nsf/All/2FBD2ACD407DEFE8C22582B9002E7019',
        web: 'http://www.dataprotection.gov.cy',
        sources: [
            'http://www.dataprotection.gov.cy/dataprotection/dataprotection.nsf/contact_el/contact_el?opendocument',
        ],
        'complaint-language': 'el',
    },
    czcuooz: {
        slug: 'czcuooz',
        'relevant-countries': ['cz'],
        name: 'Úřad pro ochranu osobních údajů (Czech Office for Personal Data Protection)',
        address: 'Pplk. Sochora 27\n170 00 Praha 7\nCzech Republic',
        phone: '+420 234 665 111',
        email: 'posta@uoou.cz',
        web: 'https://www.uoou.cz/',
        sources: ['https://www.uoou.cz/vismo/o_utvar.asp?id_org=200156&id_u=10'],
        'complaint-language': 'cs',
    },
    debawueldb: {
        slug: 'debawueldb',
        'relevant-countries': ['de'],
        name: 'Der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg',
        address: 'Postfach 10 29 32\n70025 Stuttgart\nDeutschland',
        phone: '+49 711 6155 410',
        fax: '+49 711 6155 4115',
        email: 'poststelle@lfdi.bwl.de',
        'pgp-fingerprint': 'E4FA 428C B315 2248 83BB  F6FB 0FC3 48A6 4A32 5962',
        'pgp-url': 'https://www.baden-wuerttemberg.datenschutz.de/wp-content/uploads/2020/09/LfDI-PGP-Key.txt',
        webform: 'https://www.service-bw.de/onlineantraege/onlineantrag?processInstanceId=994719535',
        web: 'https://www.baden-wuerttemberg.datenschutz.de/',
        sources: ['https://www.baden-wuerttemberg.datenschutz.de/kontakt/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    debaylda: {
        slug: 'debaylda',
        'relevant-countries': ['de'],
        name: 'Bayerisches Landesamt für Datenschutzaufsicht (BayLDA)',
        address: 'Postfach 1349\n91504 Ansbach\nDeutschland',
        phone: '+49 981 180093 0',
        fax: '+49 981 180093 800',
        email: 'poststelle@lda.bayern.de',
        webform: 'https://www.lda.bayern.de/de/beschwerde.html',
        'pgp-fingerprint': 'AB6E 5D65 D09A 043C 9953  97ED 982B BF27 609C 2220',
        'pgp-url': 'https://www.lda.bayern.de/media/pgp_schluessel_dsa.asc',
        web: 'https://www.lda.bayern.de/de/index.html',
        sources: ['https://www.lda.bayern.de/de/kontakt.html'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    debayldb: {
        slug: 'debayldb',
        'relevant-countries': ['de'],
        name: 'Der Bayerische Landesbeauftragte für den Datenschutz',
        address: 'Postfach 22 12 19\n80502 München\nDeutschland',
        phone: '+49 89 2126 72 0',
        fax: '+49 89 2126 72 50',
        email: 'poststelle@datenschutz-bayern.de',
        webform: 'https://www.datenschutz-bayern.de/service/complaint.html',
        'pgp-fingerprint': 'D576 F425 9EC5 80E7 8BC4  3A83 908F 10D5 0A6F 3BD1',
        'pgp-url': 'https://www.datenschutz-bayern.de/download/BayerDatenschutzbeauftragter.asc',
        web: 'https://www.datenschutz-bayern.de/',
        sources: ['https://www.datenschutz-bayern.de/vorstell/impressum.html'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    deberlbdi: {
        slug: 'deberlbdi',
        'relevant-countries': ['de'],
        name: 'Berliner Beauftragte für Datenschutz und Informationsfreiheit',
        address: 'Alt-Moabit 59-61\n10555 Berlin\nDeutschland',
        phone: '+49 30 138890',
        fax: '+49 30 2155050',
        email: 'mailbox@datenschutz-berlin.de',
        webform: 'https://kontakt.datenschutz-berlin.de/',
        'pgp-fingerprint': 'E60A A848 A60A 423A 9F1C  2D08 87E8 7B1C F73B 7E44',
        'pgp-url': 'https://www.datenschutz-berlin.de/fileadmin/user_upload/email/mailbox_blnbdi.asc',
        web: 'https://www.datenschutz-berlin.de',
        sources: ['https://www.datenschutz-berlin.de/ueber-uns/kontakt/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    debfdi: {
        slug: 'debfdi',
        'relevant-countries': ['de'],
        name: 'Der Bundesbeauftragte für den Datenschutz und die Informationsfreiheit',
        address: 'Graurheindorfer Str. 153\n53117 Bonn\nDeutschland',
        phone: '+49 228 997799 0',
        email: 'poststelle@bfdi.bund.de',
        webform: 'https://formulare.bfdi.bund.de/lip/action/invoke.do?id=BfDIBeschwerde',
        'pgp-fingerprint': 'D2DD 64D0 43B4 81D9 8F21  6168 FBF8 05BD BFDA 08FB',
        'pgp-url':
            'https://www.bfdi.bund.de/SharedDocs/Downloads/DE/DokumenteBfDI/BfDIKey.asc?__blob=publicationFile&v=2',
        web: 'https://www.bfdi.bund.de',
        sources: [
            'https://www.bfdi.bund.de/DE/Service/Kontakt/kontakt_node.html',
            'https://www.bfdi.bund.de/SharedDocs/Downloads/DE/DokumenteBfDI/BfDIKey.html?nn=252800',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    debralda: {
        slug: 'debralda',
        'relevant-countries': ['de'],
        name: 'Die Landesbeauftragte für den Datenschutz und für das Recht auf Akteneinsicht Brandenburg',
        address: 'Stahnsdorfer Damm 77\n14532 Kleinmachnow\nDeutschland',
        phone: '+49 33203 356 0',
        fax: '+49 33203 356 49',
        email: 'poststelle@lda.brandenburg.de',
        webform: 'https://www.lda.brandenburg.de/lda/de/service/formulare-und-musterschreiben/beschwerdeformular/',
        'pgp-fingerprint': 'D0D7 0D36 C6F9 F97C 74AA  33AB 1386 F557 7511 8EC7',
        'pgp-url': 'https://www.lda.brandenburg.de/sixcms/media.php/9/LDABbgPublickey.asc',
        web: 'https://www.lda.brandenburg.de',
        sources: [
            'https://www.lda.brandenburg.de/lda/de/ueber-uns/kontakt/',
            'https://www.lda.brandenburg.de/lda/de/ueber-uns/kontakt/pgp-schluessel/',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    debrelfdi: {
        slug: 'debrelfdi',
        'relevant-countries': ['de'],
        name: 'Die Landesbeauftragte für Datenschutz und Informationsfreiheit Bremen',
        address: 'Arndtstraße 1\n27570 Bremerhaven\nDeutschland',
        phone: '+49 421 3612 010',
        email: 'office@datenschutz.bremen.de',
        webform: 'https://www.datenschutz.bremen.de/wir-ueber-uns/online-meldungen/beschwerdeformular-15253',
        'pgp-fingerprint': '7083 9D74 276A D4FA 970D  272B 6B52 8D07 5B7D 02B2',
        'pgp-url': 'https://www.datenschutz.bremen.de/sixcms/media.php/13/lfdi_bremen.asc',
        web: 'https://www.datenschutz.bremen.de/',
        sources: [
            'https://www.datenschutz.bremen.de/wir_ueber_uns/vertrauliche_kommunikation-7303',
            'https://www.datenschutz.bremen.de/impressum-1478',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    dedsbkd: {
        slug: 'dedsbkd',
        'relevant-countries': ['de'],
        name: 'Der Datenschutzbeauftragte für Kirche und Diakonie',
        address: 'Reichenbrander Str. 4\n09117 Chemnitz\nDeutschland',
        phone: '+49 351 4692 460',
        fax: '+49 351 4692 469',
        email: 'datenschutzbeauftragter@evlks.de',
        web: 'https://dsbkd.de/',
        sources: ['https://dsbkd.de/kontakt/', 'https://dsbkd.de/datenschutzerklaerung/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    deekdbfd: {
        slug: 'deekdbfd',
        'relevant-countries': ['de'],
        name: 'Der Beauftragte für den Datenschutz der EKD',
        address: 'Lange Laube 20\n30159 Hannover\nDeutschland',
        phone: '+49 511 768 128 0',
        fax: '+49 511 768 128 20',
        email: 'info@datenschutz.ekd.de',
        'pgp-fingerprint': 'EB37 8F76 4253 6A45 2721  5C47 3C85 1F4B E5F2 AD13',
        'pgp-url': 'https://datenschutz.ekd.de/wp-content/uploads/2015/05/3C851F4BE5F2AD13.asc',
        web: 'https://datenschutz.ekd.de',
        sources: ['https://datenschutz.ekd.de/kontakt/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    deevpfalz: {
        slug: 'deevpfalz',
        'relevant-countries': ['de'],
        name: 'Datenschutzbeauftragte Evangelische Kirche der Pfalz',
        address: 'Domplatz 5\n67346 Speyer\nDeutschland',
        phone: '+49 6232 667 434',
        fax: '+49 6232 667 6434',
        email: 'pia.schneider@evkirchepfalz.de',
        web: 'https://www.evkirchepfalz.de/landeskirche/beauftragte-und-sachverstaendige/',
        sources: ['https://datenschutz.ekd.de/vernetzung/andere-evangelisch/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    dehessbdi: {
        slug: 'dehessbdi',
        'relevant-countries': ['de'],
        name: 'Der Hessische Beauftragte für Datenschutz und Informationsfreiheit',
        address: 'Postfach 3163\n65021 Wiesbaden\nDeutschland',
        phone: '+49 611 1408 0',
        email: 'poststelle@datenschutz.hessen.de',
        webform: 'https://datenschutz.hessen.de/service/beschwerde-uebermitteln',
        'pgp-fingerprint': 'DAC0 B9DA 6EE9 6E28 BC99  F6E0 634F A712 DA3A 9839',
        'pgp-url': 'https://datenschutz.hessen.de/sites/datenschutz.hessen.de/files/2022-10/hbdi_pgp.txt',
        web: 'https://datenschutz.hessen.de/',
        sources: [
            'https://datenschutz.hessen.de/impressum',
            'https://datenschutz.hessen.de/ueber-uns/verschluesselte-kommunikation',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    dehmbbfdi: {
        slug: 'dehmbbfdi',
        'relevant-countries': ['de'],
        name: 'Der Hamburgische Beauftragte für Datenschutz und Informationsfreiheit',
        address: 'Ludwig-Erhard-Str 22, 7. OG\n20459 Hamburg\nDeutschland',
        phone: '+49 40 428 54 4040',
        fax: '+49 40 4279 11 4000',
        email: 'mailbox@datenschutz.hamburg.de',
        webform: 'https://datenschutz-hamburg.de/beschwerde/',
        'pgp-fingerprint': '0932 579B 33C1 8C21 6C9D  E77D 08DD BAE4 3377 5707',
        'pgp-url': 'https://datenschutz-hamburg.de/assets/misc/pgp-schluessel-hmbbfdi.asc',
        web: 'https://datenschutz-hamburg.de/',
        sources: ['https://datenschutz-hamburg.de/pages/dienststelle/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    dekathbayddsb: {
        slug: 'dekathbayddsb',
        'relevant-countries': ['de'],
        name: 'Diözesandatenschutzbeauftragter Bayerische Bistümer',
        address: 'Kapellenstr. 4\n80333 München\nDeutschland',
        phone: '+49 89 21 37 17 96',
        email: 'jjoachimski@eomuc.de',
        sources: ['https://www.erzbistum-muenchen.de/ordinariat/datenschutzstelle'],
        'complaint-language': 'de',
        comments: [
            'Zuständig für Bayerische Bistümer:\n\nBistum Augsburg\nErzbistum Bamberg\nBistum Eichstätt\nErzbistum München & Freising\nBistum Passau\nBistum Regensburg\nBistum Würzburg',
        ],
    },
    dekathdsz: {
        slug: 'dekathdsz',
        'relevant-countries': ['de'],
        name: 'Katholisches Datenschutzzentrum (KdöR)',
        address: 'Brackeler Hellweg 144\n44309 Dortmund\nDeutschland',
        phone: '+49 231 13 89 85 0',
        fax: '+49 231 13 89 85 22',
        email: 'info@kdsz.de',
        web: 'https://www.katholisches-datenschutzzentrum.de/',
        sources: [
            'https://www.katholisches-datenschutzzentrum.de/wir-ueber-uns/team-katholisches-datenschutzzentrum/',
            'https://www.datenschutz-kirche.de/%C3%BCbersicht_aufsichtsbeh%C3%B6rden',
        ],
        'complaint-language': 'de',
        comments: [
            'Zuständig für nordrhein-westfälische Bistümer:\n\nBistum Aachen\nBistum Essen\nErzbistum Köln\nBistum Münster (nordrhein-westfälischer Teil)\nErzbistum Paderborn',
        ],
    },
    dekathffdsz: {
        slug: 'dekathffdsz',
        'relevant-countries': ['de'],
        name: 'Katholisches Datenschutzzentrum Frankfurt/M. KdöR (Mittel- und Südwestdeutsche Bistümer)',
        address: 'Domplatz 3\nHaus am Dom\n60311 Frankfurt/M.\nDeutschland',
        phone: '+49 69 800 871 8800',
        fax: '+49 69 800 871 8815',
        email: 'info@kdsz-ffm.de',
        web: 'https://www.kath-datenschutzzentrum-ffm.de/',
        sources: ['https://www.kath-datenschutzzentrum-ffm.de/impressum/'],
        'complaint-language': 'de',
        comments: [
            'Zuständig für mittel- und südwestdeutsche Bistümer:\n\nErzbistum Freiburg\nBistum Fulda\nBistum Limburg\nBistum Mainz\nBistum Stuttgart Rottenburg\nBistum Speyer und Trier',
        ],
    },
    dekathnordddsb: {
        slug: 'dekathnordddsb',
        'relevant-countries': ['de'],
        name: 'Katholische Datenschutzaufsicht Nord für das Erzbistum Hamburg, die Bistümer Hildesheim und Osnabrück und das Bischöflich Münstersche Offizialat in Vechta i.O.',
        address: 'Unser Lieben Frauen Kirchhof 20\n28195 Bremen\nDeutschland',
        phone: '+49 421 33 00 56 0',
        email: 'info@kdsa-nord.de',
        webform: 'https://www.kdsa-nord.de/beschwerde_einreichen',
        web: 'https://www.kdsa-nord.de/',
        sources: ['https://www.kdsa-nord.de/kontakt'],
        'complaint-language': 'de',
        comments: [
            'Zuständig für norddeutsche Bistümer:\n\nErzbistum Hamburg\nBistum Hildesheim\nBistum Osnabrück\nBistum Münster (niedersächsischer Teil)',
        ],
    },
    dekathostddsb: {
        slug: 'dekathostddsb',
        'relevant-countries': ['de'],
        name: 'Kirchliche Datenschutzaufsicht der ostdeutschen Bistümer und des Katholischen Militärbischofs',
        address: 'Badepark 4\n39218 Schönebeck\nDeutschland',
        phone: '+49 3928 7179018',
        fax: '+49 3928 7179019',
        email: 'kontakt@kdsa-ost.de',
        webform: 'https://www.kdsa-ost.de/datenschutzbeschwerde.html',
        web: 'https://www.kdsa-ost.de/',
        sources: ['https://www.kdsa-ost.de/kontaktformular.html'],
        'complaint-language': 'de',
        comments: [
            'Zuständig für ostdeutsche Bistümer:\n\nErzbistum Berlin\nBistum Dresden-Meißen\nBistum Erfurt\nBistum Görlitz\nBistum Magdeburg',
        ],
    },
    demvldi: {
        slug: 'demvldi',
        'relevant-countries': ['de'],
        name: 'Der Landesbeauftragte für Datenschutz und Informationsfreiheit Mecklenburg-Vorpommern',
        address: 'Schloss Schwerin\nLennéstraße 1\n19053 Schwerin\nDeutschland',
        phone: '+49 385 59494 0',
        email: 'info@datenschutz-mv.de',
        webform:
            'https://www.datenschutz-mv.de/kontakt/online-beschwerdeformular-mitteilung-ueber-einen-datenschutzverstoss/',
        'pgp-fingerprint': '66E5 EB3B C2F0 E8B7 4D70  0A66 DA65 6823 63BE 680F',
        'pgp-url': 'https://www.datenschutz-mv.de/static/DS/Dateien/pgp_lds_mv.asc',
        web: 'https://www.datenschutz-mv.de/',
        sources: [
            'https://www.datenschutz-mv.de/kontakt',
            'https://www.datenschutz-mv.de/datenschutzerklaerung/#email',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    dendslfd: {
        slug: 'dendslfd',
        'relevant-countries': ['de'],
        name: 'Die Landesbeauftragte für den Datenschutz Niedersachsen',
        address: 'Postfach 221\n30002 Hannover\nDeutschland',
        phone: '+49 511 120 4500',
        fax: '+49 511 120 4599',
        email: 'poststelle@lfd.niedersachsen.de',
        webform: 'https://www.navo.niedersachsen.de/navo2/portal/csend/8915/fileget/dsbeschwerdeformular.html',
        'pgp-fingerprint': '6194 AE01 4804 7C0C 915C  E1F8 21F1 4CA5 91F3 F7A7',
        'pgp-url': 'https://lfd.niedersachsen.de/download/32009',
        web: 'https://lfd.niedersachsen.de/startseite/',
        sources: [
            'https://lfd.niedersachsen.de/wir_ueber_uns/so_erreichen_sie_uns/so-erreichen-sie-uns-56182.html',
            'https://lfd.niedersachsen.de/wir_ueber_uns/hinweis_zur_eroeffnung_zugangs_elektronischer_kommunikation/hinweis-zur-eroeffnung-des-zugangs-elektronischer-kommunikation-56046.html',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    denrwldi: {
        slug: 'denrwldi',
        'relevant-countries': ['de'],
        name: 'Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen',
        address: 'Kavalleriestraße 2 - 4\n40213 Düsseldorf\nDeutschland',
        phone: '+49 211 38424 0',
        fax: '+49 211 38424 999',
        email: 'poststelle@ldi.nrw.de',
        'pgp-fingerprint': 'EA14 18FA B79C A892 B172  850D 5C01 04F6 43DF 6F2E',
        'pgp-url': 'https://www.ldi.nrw.de/pgp-schluessel',
        web: 'https://www.ldi.nrw.de/',
        sources: ['https://www.ldi.nrw.de/kontakt', 'https://www.ldi.nrw.de/kontakt/ihre-beschwerde'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    derf: {
        slug: 'derf',
        'relevant-countries': ['de'],
        name: 'Der Rundfunkdatenschutzbeauftragte von BR, HR, MDR, SR, SWR, WDR, Deutschlandradio und ZDF',
        address: 'Kantstr. 71-73\n04275 Leipzig\nDeutschland',
        phone: '+49 341 300 6240',
        fax: '+49 341 300 29 6240',
        email: 'kontakt@rundfunkdatenschutz.de',
        webform: 'https://www.rundfunkdatenschutz.de/buergerinnen-und-buerger/beschwerden/',
        web: 'https://www.rundfunkdatenschutz.de/',
        sources: ['https://www.rundfunkdatenschutz.de/impressum/'],
        'suggested-transport-medium': 'email',
    },
    derfdw: {
        slug: 'derfdw',
        'relevant-countries': ['de'],
        name: 'Rundfunkdatenschutzbeauftragter Deutsche Welle',
        address: 'Kurt-Schumacher-Straße 3\n53113 Bonn\nDeutschland',
        phone: '+49 228 4292123',
        fax: '+49 228 4292120',
        email: 'datenschutz@dw.com',
        web: 'https://www.dw.com/de/datenschutzbericht/a-16130989',
        sources: [
            'https://www.rundfunkdatenschutzkonferenz.de/kontakt',
            'https://www.bfdi.bund.de/SharedDocs/Adressen/DE/Rundfunkdatenschutzbeauftragte/DatenschutzbeauftragterDeutscheWelle.html',
        ],
        'suggested-transport-medium': 'email',
    },
    derfndr: {
        slug: 'derfndr',
        'relevant-countries': ['de'],
        name: 'Rundfunkdatenschutzbeauftragter Norddeutscher Rundfunk',
        address: 'Rothenbaumchaussee 132\n20149 Hamburg\nDeutschland',
        phone: '+49 40 41562236',
        fax: '+49 40 41563452',
        email: 'datenschutz@ndr.de',
        web: 'https://www.ndr.de/der_ndr/unternehmen/organisation/Datenschutz-beimNDR,datenschutz6.html',
        sources: [
            'https://www.rundfunkdatenschutzkonferenz.de/kontakt',
            'https://www.bfdi.bund.de/SharedDocs/Adressen/DE/Rundfunkdatenschutzbeauftragte/DatenschutzbeauftragterNorddeutscherRundfunk.html',
        ],
        'suggested-transport-medium': 'email',
    },
    derfrb: {
        slug: 'derfrb',
        'relevant-countries': ['de'],
        name: 'Datenschutzbeauftragte Radio Bremen',
        address: 'Diepenau 10\n28195 Bremen\nDeutschland',
        phone: '+49 421 24641029',
        fax: '+49 421 24641097',
        email: 'datenschutz@radiobremen.de',
        web: 'https://www.radiobremen.de/info/datenschutz/datenschutz-beauftragte-106.html',
        sources: [
            'https://www.radiobremen.de/info/datenschutz/datenschutz-beauftragte-106.html',
            'https://www.bfdi.bund.de/SharedDocs/Adressen/DE/Rundfunkdatenschutzbeauftragte/DatenschutzbeauftragterRadioBremen.html',
        ],
        'suggested-transport-medium': 'email',
    },
    derfrbb: {
        slug: 'derfrbb',
        'relevant-countries': ['de'],
        name: 'Datenschutzbeauftragte Rundfunk Berlin-Brandenburg',
        address: 'Masurenallee 8-14\n14057 Berlin\nDeutschland',
        phone: '+49 30 9799310400',
        fax: '+49 30 9799360109',
        email: 'datenschutz@rbb-online.de',
        web: 'https://www.rbb-online.de/unternehmen/der_rbb/struktur/datenschutz/datenschutz_im_rbb.html',
        sources: [
            'https://www.rbb-online.de/unternehmen/der_rbb/struktur/datenschutz/kontakt.html',
            'https://www.bfdi.bund.de/SharedDocs/Adressen/DE/Rundfunkdatenschutzbeauftragte/DatenschutzbeauftragteRundfunkBerlin-Brandenburg.html',
        ],
        'suggested-transport-medium': 'email',
    },
    derlpbdi: {
        slug: 'derlpbdi',
        'relevant-countries': ['de'],
        name: 'Der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Rheinland-Pfalz',
        address: 'Postfach 30 40\n55020 Mainz\nDeutschland',
        phone: '+49 6131 8920 0',
        fax: '+49 6131 8920 299',
        email: 'poststelle@datenschutz.rlp.de',
        webform: 'https://www.datenschutz.rlp.de/de/themenfelder-themen/online-services/beschwerdeformular/',
        'pgp-fingerprint': 'FD66 9C75 8F5C 660C 6FBD  A58C A830 93C0 2FB7 C9F5',
        'pgp-url': 'https://www.datenschutz.rlp.de/fileadmin/lfdi/Dokumente/pubkey_lfdi-rlp.asc',
        web: 'https://www.datenschutz.rlp.de',
        sources: ['https://www.datenschutz.rlp.de/de/themenfelder-themen/kontakt/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    desaarudz: {
        slug: 'desaarudz',
        'relevant-countries': ['de'],
        name: 'Unabhängiges Datenschutzzentrum Saarland',
        address: 'Fritz-Dobisch-Straße 12\n66111 Saarbrücken\nDeutschland',
        phone: '+49 681 94781 0',
        fax: '+49 681 94781 29',
        email: 'poststelle@datenschutz.saarland.de',
        webform: 'https://www.datenschutz.saarland.de/online-dienste/beschwerdeformular',
        'pgp-fingerprint': 'F94D 5562 FEA3 27B7 D4E6  898F 07CF 5ADF 4B44 088A',
        'pgp-url': 'https://www.datenschutz.saarland.de/fileadmin/schluessel/datenschutzzentrum-pubkey.asc',
        web: 'https://datenschutz.saarland.de/',
        sources: [
            'https://www.datenschutz.saarland.de/ueber-uns/kontakt-und-erreichbarkeit',
            'https://www.datenschutz.saarland.de/impressum',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    desaechsdsb: {
        slug: 'desaechsdsb',
        'relevant-countries': ['de'],
        name: 'Sächsische Datenschutz- und Transparenzbeauftragte',
        address: 'Postfach 11 01 32\n01330 Dresden\nDeutschland',
        phone: '+49 351 85471 101',
        fax: '+49 351 85471 109',
        email: 'post@sdtb.sachsen.de',
        webform: 'https://formulare.datenschutz.sachsen.de/form/provide/53/',
        'pgp-fingerprint': 'E208 1C36 DCFC F7AB AEF7  335A 617F 849E 63C3 BB05',
        'pgp-url': 'https://www.datenschutz.sachsen.de/download/SDTB_Post.asc',
        web: 'https://www.datenschutz.sachsen.de',
        sources: ['https://www.datenschutz.sachsen.de/kontakt.html'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    desalbd: {
        slug: 'desalbd',
        'relevant-countries': ['de'],
        name: 'Landesbeauftragter für den Datenschutz Sachsen-Anhalt',
        address: 'Postfach 1947\n39009 Magdeburg\nDeutschland',
        phone: '+49 391 81803 0',
        fax: '+49 391 81803 33',
        email: 'poststelle@lfd.sachsen-anhalt.de',
        webform: 'https://datenschutz.sachsen-anhalt.de/service/online-formulare/beschwerde-anfrage',
        'pgp-fingerprint': '5CBB 4E15 9774 8921 3B27  7C96 DE25 9BE2 09AC A0DE',
        'pgp-url':
            'https://datenschutz.sachsen-anhalt.de/fileadmin/Bibliothek/Landesaemter/LfD/PDF/binary/Landesbeauftragter/Anschrift/E-Mail/LfD_ST_Public_Key.asc',
        web: 'https://datenschutz.sachsen-anhalt.de',
        sources: [
            'https://datenschutz.sachsen-anhalt.de/landesbeauftragter/kontakt/',
            'https://datenschutz.sachsen-anhalt.de/landesbeauftragter/kontakt/wichtige-hinweise-zum-e-mail-versand',
        ],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    deshuld: {
        slug: 'deshuld',
        'relevant-countries': ['de'],
        name: 'Unabhängiges Landeszentrum für Datenschutz Schleswig-Holstein',
        address: 'Postfach 71 16\n24171 Kiel\nDeutschland',
        phone: '+49 431 988 1200',
        fax: '+49 431 988 1223',
        email: 'mail@datenschutzzentrum.de',
        webform: 'https://www.datenschutzzentrum.de/formular/beschwerde.php',
        'pgp-fingerprint': 'C41A F0B6 CCA3 2862 FAF5  3728 CB6D 2152 E25B 69E4',
        'pgp-url': 'https://www.datenschutzzentrum.de/uploads/uld/uld.asc',
        web: 'https://www.datenschutzzentrum.de/',
        sources: ['https://www.datenschutzzentrum.de/impressum/'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    detlfdi: {
        slug: 'detlfdi',
        'relevant-countries': ['de'],
        name: 'Thüringer Landesbeauftragter für den Datenschutz und die Informationsfreiheit',
        address: 'Postfach 900455\n99107 Erfurt\nDeutschland',
        phone: '+49 361 57 311 29 00',
        fax: '+49 361 57 311 29 04',
        email: 'poststelle@datenschutz.thueringen.de',
        'pgp-fingerprint': 'F22C 242B DE79 A9E6 58C5  258E C10D 6A44 E2F5 11A2',
        'pgp-url': 'https://www.tlfdi.de/fileadmin/tlfdi/wir-ueber-uns/tlfdi_schluessel_ab_2020.txt',
        web: 'https://www.tlfdi.de',
        sources: ['https://www.tlfdi.de/kontakt'],
        'complaint-language': 'de',
        'suggested-transport-medium': 'email',
    },
    dkdi: {
        slug: 'dkdi',
        'relevant-countries': ['dk'],
        name: 'Datatilsynet (Data Inspectorate of Denmark)',
        address: 'Carl Jacobsens Vej 35\n2500 Valby\nDenmark',
        phone: '+45 33 19 32 00',
        fax: '+45 33 19 32 18',
        email: 'dt@datatilsynet.dk',
        web: 'https://www.datatilsynet.dk/',
        sources: ['https://www.datatilsynet.dk/kontakt/'],
        'complaint-language': 'da',
    },
    eeaki: {
        slug: 'eeaki',
        'relevant-countries': ['ee'],
        name: 'Andmekaitse Inspektsioon (Estonian Data Protection Inspectorate)',
        address: '39 Tatari St.\n10134 Tallinn\nEstonia',
        phone: '+372 627 4135',
        email: 'info@aki.ee',
        web: 'http://www.aki.ee/',
        sources: ['https://www.aki.ee/en/contacts'],
        'complaint-language': 'et',
    },
    esaepa: {
        slug: 'esaepa',
        'relevant-countries': ['es'],
        name: 'Agencia Española de Protección de Datos (Spanish Agency for Data Protection)',
        address: 'C/ Jorge Juan, 6\n28001 Madrid\nSpain',
        phone: '+34 900 293 183',
        fax: '+34 900 293 621',
        webform: 'https://sedeagpd.gob.es/sede-electronica-web/vistas/infoSede/tramitesCiudadano.jsf',
        web: 'https://www.aepd.es/',
        sources: [
            'https://www.aepd.es/agencia/contacto.html',
            'http://ec.europa.eu/newsroom/article29/item-detail.cfm?item_id=612080',
        ],
        'complaint-language': 'es',
    },
    fitst: {
        slug: 'fitst',
        'relevant-countries': ['fi'],
        name: 'Tietosuojavaltuutetun toimisto (Office of the Data Protection Ombudsman of Finland)',
        address: 'PL 800\n00531 Helsinki\nFinland',
        phone: '+358 29 566 6700',
        fax: '+358 29 566 6735',
        email: 'tietosuoja@om.fi',
        webform: 'https://tietosuoja.fi/ilmoitus-tietosuojavaltuutetulle',
        web: 'https://tietosuoja.fi',
        sources: ['https://tietosuoja.fi/en/contact-information'],
        'complaint-language': 'fi',
    },
    frcnil: {
        slug: 'frcnil',
        'relevant-countries': ['fr'],
        name: "Commission Nationale de l'Informatique et des Libertés – CNIL (French National Commission on Informatics and Liberty)",
        address: '3 Place de Fontenoy\nTSA 80715\n75334 PARIS CEDEX 07\nFrance',
        phone: '+33 1 53 73 22 22',
        webform: 'https://www.cnil.fr/fr/plaintes',
        web: 'https://www.cnil.fr/',
        sources: ['https://www.cnil.fr/fr/contacter-la-cnil-standard-et-permanences-telephoniques'],
        'complaint-language': 'fr',
    },
    gbico: {
        slug: 'gbico',
        'relevant-countries': ['gb'],
        name: 'The Information Commissioner’s Office',
        address: 'Wycliffe House\nWater Lane\nWilmslow\nCheshire\nSK9 5AF\nUnited Kingdom',
        phone: '+44 303 123 1113',
        fax: '+44 162 552 4510',
        webform: 'https://ico.org.uk/make-a-complaint/data-protection-complaints/data-protection-complaints/',
        web: 'https://ico.org.uk/',
        sources: ['https://ico.org.uk/about-the-ico/who-we-are/directions-head-office/'],
        'complaint-language': 'en',
    },
    grdpa: {
        slug: 'grdpa',
        'relevant-countries': ['gr'],
        name: 'Αρχή Προστασίας Δεδομένων Προσωπικού Χαρακτήρα (Hellenic Data Protection Authority)',
        address: 'Kifissias 1 – 3\n115 23 Athens\nGreece',
        phone: '+30 210 64756 00',
        email: 'complaints@dpa.gr',
        web: 'https://www.dpa.gr/',
        sources: ['https://www.dpa.gr/index.php/en/individuals/complaint-to-the-hellenic-dpa'],
        'complaint-language': 'el',
    },
    hrazop: {
        slug: 'hrazop',
        'relevant-countries': ['hr'],
        name: 'Agencija za zaštitu osobnih podataka (Croatian Personal Data Protection Agency)',
        address: 'Selska cesta 136\n10 000 Zagreb\nCroatia',
        phone: '+385 1 4609 000',
        fax: '+385 1 4609 099',
        email: 'azop@azop.hr',
        webform: 'https://azop.hr/zahtjev-za-utvrdivanje-povrede-prava/',
        web: 'https://azop.hr/',
        sources: ['https://azop.hr/contact/'],
        'complaint-language': 'hr',
    },
    hunaih: {
        slug: 'hunaih',
        'relevant-countries': ['hu'],
        name: 'Nemzeti Adatvédelmi és Információszabadság Hatóság (Hungarian National Authority for Data Protection and Freedom of Information)',
        address: 'Budapest\nPf.: 9.\n1363\nHungary',
        phone: '+36 1 391 1400',
        fax: '+36 1 391 1410',
        email: 'ugyfelszolgalat@naih.hu',
        web: 'https://www.naih.hu/',
        sources: ['https://naih.hu/ugyfelszolgalat-kapcsolat'],
        'complaint-language': 'hu',
    },
    iedpc: {
        slug: 'iedpc',
        'relevant-countries': ['ie'],
        name: 'Irish Data Protection Commission',
        address: '21 Fitzwilliam Square South\nDublin 2\nD02 RD28\nIreland',
        phone: '+353 1800 437 737',
        email: 'info@dataprotection.ie',
        webform: 'https://forms.dataprotection.ie/contact',
        web: 'https://www.dataprotection.ie',
        sources: [
            'https://www.dataprotection.ie/en/contact/how-contact-us',
            'https://www.dataprotection.ie/holding.html',
        ],
        'complaint-language': 'en',
    },
    isdpa: {
        slug: 'isdpa',
        'relevant-countries': ['is'],
        name: 'Persónuvernd (Icelandic Data Protection Authority)',
        address: 'Rauðarárstígur 10\n105 Reykjavík\nIceland',
        phone: '+354 510 9600',
        email: 'postur@personuvernd.is',
        web: 'https://www.personuvernd.is/',
        sources: ['https://www.personuvernd.is/information-in-english/about-us/'],
        'complaint-language': 'is',
    },
    itgpdp: {
        slug: 'itgpdp',
        'relevant-countries': ['it'],
        name: 'Garante per la protezione dei dati personali (Italian Data Protection Authority)',
        address: 'Piazza Venezia 11\n00187 Roma\nItaly',
        phone: '+39 06 69677 1',
        email: 'protocollo@pec.gpdp.it',
        web: 'https://www.garanteprivacy.it/',
        sources: ['https://www.garanteprivacy.it/web/garante-privacy-en'],
        'complaint-language': 'it',
    },
    lidss: {
        slug: 'lidss',
        'relevant-countries': ['li'],
        name: 'Datenschutzstelle (DSS) Fürstentum Liechtenstein',
        address: 'Städtle 38\nPostfach 684\n9490 Vaduz\nLiechtenstein',
        phone: '+423 236 60 90',
        email: 'info.dss@llv.li',
        webform: 'http://formulare.llv.li/formserver_DSS/start.do?generalid=DSS_BF',
        web: 'https://www.datenschutzstelle.li/',
        sources: ['https://www.datenschutzstelle.li/impressum'],
        'complaint-language': 'de',
    },
    ltada: {
        slug: 'ltada',
        'relevant-countries': ['lt'],
        name: 'Valstybinė duomenų apsaugos inspekcija (State Data Protection Inspectorate of Lithuania)',
        address: 'L. Sapiegos str. 17\n10312 Vilnius\nLithuania',
        phone: '+370 5 271 2804',
        fax: '+370 5 261 9494',
        email: 'ada@ada.lt',
        web: 'https://vdai.lrv.lt/',
        sources: ['https://vdai.lrv.lt/en/'],
        'complaint-language': 'lt',
    },
    lucnpd: {
        slug: 'lucnpd',
        'relevant-countries': ['lu'],
        name: 'Commission nationale pour la protection des données (National Commission for Data Protection, Grand-Duchy of Luxembourg)',
        address: '15, Boulevard du Jazz\nL-4370 Belvaux\nLuxembourg',
        phone: '+352 26 10 60 1',
        fax: '+352 26 10 60 29',
        email: 'info@cnpd.lu',
        webform: 'https://cnpd.public.lu/en/particuliers/faire-valoir/formulaire-plainte.html',
        web: 'https://cnpd.public.lu',
        sources: [
            'https://cnpd.public.lu/de/support/contact.html',
            'https://cnpd.public.lu/en/support/protection-des-donnees.html',
        ],
    },
    lvdvi: {
        slug: 'lvdvi',
        'relevant-countries': ['lv'],
        name: 'Datu valsts inspekcija (Data State Inspectorate of Latvia)',
        address: 'Elijas iela 17\nRiga\nLV-1050\nLatvia',
        phone: '+371 67 223 131',
        email: 'pasts@dvi.gov.lv',
        web: 'https://www.dvi.gov.lv/',
        sources: ['https://www.dvi.gov.lv/lv/iestades-kontakti'],
        'complaint-language': 'lv',
    },
    mtidpc: {
        slug: 'mtidpc',
        'relevant-countries': ['mt'],
        name: 'Office of the Information and Data Protection Commissioner of Malta',
        address: 'Floor 2, Airways House\nTriq Il-Kbira\nTas-Sliema SLM 1549\nMalta',
        phone: '+356 2328 7100',
        email: 'idpc.info@idpc.org.mt',
        webform: 'https://register.idpc.org.mt/report-breach/complaint/',
        web: 'https://idpc.org.mt',
        sources: ['https://idpc.org.mt/contact/'],
        'complaint-language': 'en',
    },
    nlap: {
        slug: 'nlap',
        'relevant-countries': ['nl'],
        name: 'Autoriteit Persoonsgegevens (Dutch Data Protection Authority)',
        address: 'Postbus 93374\n2509 AJ DEN HAAG\nThe Netherlands',
        phone: '+31 70 888 85 00',
        fax: '+31 70 888 85 01',
        email: 'info@autoriteitpersoonsgegevens.nl',
        webform: 'https://autoriteitpersoonsgegevens.nl/nl/meldingsformulier-klachten',
        web: 'https://autoriteitpersoonsgegevens.nl',
        sources: ['https://autoriteitpersoonsgegevens.nl/en/contact-dutch-dpa/contact-us'],
        'complaint-language': 'nl',
    },
    nods: {
        slug: 'nods',
        'relevant-countries': ['no'],
        name: 'Datatilsynet (Norwegian Data Protection Authority)',
        address: 'Postboks 458 Sentrum\n0105 Oslo\nNorway',
        phone: '+47 22 39 69 00',
        email: 'postkasse@datatilsynet.no',
        'pgp-url':
            'https://www.datatilsynet.no/globalassets/global/dokumenter-pdfer-skjema-ol/om-datatilsynet/kryptering-ved-openpgp/datatilsynet.pub.asc',
        'pgp-fingerprint': '5444 4EE6 F919 6139 CEEA  6787 218A ACA7 25B7 D71A',
        web: 'https://www.datatilsynet.no/',
        sources: ['https://www.datatilsynet.no/om-datatilsynet/kontakt-oss/'],
        'suggested-transport-medium': 'letter',
        'complaint-language': 'no',
    },
    plgiodo: {
        slug: 'plgiodo',
        'relevant-countries': ['pl'],
        name: 'UODO – Urząd Ochrony Danych Osobowych (Personal Data Protection Office of Poland)',
        address: 'ul. Stawki 2\n00-193 Warszawa\nPoland',
        phone: '+48 22 531 03 00',
        email: 'kancelaria@uodo.gov.pl',
        web: 'https://www.uodo.gov.pl/',
        sources: ['https://www.uodo.gov.pl/en/484', 'https://www.uodo.gov.pl/pl/p/kontakt'],
        'complaint-language': 'pl',
    },
    ptcnpd: {
        slug: 'ptcnpd',
        'relevant-countries': ['pt'],
        name: 'CNPD – Comissão Nacional de Protecção de Dados',
        address: 'Av. D. Carlos I, 134 - 1.º\n1200-651 Lisboa\nPortugal',
        phone: '+351 21 392 84 00',
        fax: '+351 21 397 68 32',
        email: 'geral@cnpd.pt',
        web: 'https://www.cnpd.pt',
        sources: ['https://www.cnpd.pt/politica-de-privacidade/'],
        'complaint-language': 'pt',
    },
    roanspdcp: {
        slug: 'roanspdcp',
        'relevant-countries': ['ro'],
        name: 'Autoritatea Naţională de Supraveghere a Prelucrării Datelor cu Caracter Personal (The National Supervisory Authority For Personal Data Processing of Romania)',
        address: 'B-dul G-ral. Gheorghe Magheru 28-30\nSector 1, cod postal 010336\nBucuresti\nRomania',
        phone: '+40 318 059 211',
        fax: '+40 318 059 602',
        email: 'anspdcp@dataprotection.ro',
        webform: 'https://www.dataprotection.ro/index.jsp?page=Plangeri_pagina_principala',
        web: 'https://www.dataprotection.ro/',
        sources: ['https://www.dataprotection.ro/index.jsp?page=contact'],
    },
    sedi: {
        slug: 'sedi',
        'relevant-countries': ['se'],
        name: 'Integritetsskyddsmyndigheten (Swedish Data Protection Authority)',
        address: 'Box 8114\n104 20 Stockholm\nSweden',
        phone: '+46 8 657 61 00',
        email: 'imy@imy.se',
        web: 'https://www.imy.se/',
        sources: ['https://www.imy.se/om-oss/kontakta-oss/'],
        'complaint-language': 'sv',
    },
    siiprs: {
        slug: 'siiprs',
        'relevant-countries': ['si'],
        name: 'Informacijski pooblaščenec (Information Commissioner of the Republic of Slovenia)',
        address: 'Dunajska cesta 22\n1000 Ljubljana\nSlovenia',
        phone: '+386 1 230 97 30',
        email: 'gp.ip@ip-rs.si',
        web: 'https://www.ip-rs.si/',
        sources: ['https://www.ip-rs.si/en/about/about/'],
        'complaint-language': 'sl',
    },
    skunoou: {
        slug: 'skunoou',
        'relevant-countries': ['sk'],
        name: 'Úrad na ochranu osobných údajov Slovenskej republiky (Office for Personal Data Protection of the Slovak Republic)',
        address: 'Hraničná 12\n820 07 Bratislava 27\nSlovakia',
        phone: '+421 2 323 132 14',
        fax: '+421 2 323 132 34',
        email: 'statny.dozor@pdp.gov.sk',
        web: 'https://dataprotection.gov.sk/uoou/',
        sources: [
            'https://dataprotection.gov.sk/uoou/node/148',
            'https://dataprotection.gov.sk/uoou/en/content/contact',
        ],
        'complaint-language': 'sk',
    },
} as const;

const dpaOverrides: Partial<Record<keyof typeof dpaData, { languages: string[] }>> = {
    lucnpd: { languages: ['en', 'de', 'fr'] },
    dkdi: { languages: ['en', 'da'] },
    roanspdcp: { languages: ['en', 'ro'] },
    cydp: { languages: ['en', 'el'] },
    bgcpdp: { languages: ['bg'] },
    nods: { languages: ['no'] },
    lidss: { languages: ['de', 'en'] },
    atdsb: { languages: ['de'] },
    lvdvi: { languages: ['lv'] },
    itgpdp: { languages: ['it'] },
    grdpa: { languages: ['en', 'el'] },
    mtidpc: { languages: ['en', 'mt'] },
    sedi: { languages: ['en', 'sv'] },
    siiprs: { languages: ['en', 'sl'] },
    hunaih: { languages: ['hu'] },
    isdpa: { languages: ['is'] },
    fitst: { languages: ['en', 'fi', 'sv'] },
    plgiodo: { languages: ['pl'] },
    czcuooz: { languages: ['cs'] },
    skunoou: { languages: ['sk'] },
    ltada: { languages: ['lt'] },
    beapd: { languages: ['fr', 'nl', 'de'] },
    hrazop: { languages: ['hr'] },
    eeaki: { languages: ['et'] },
    frcnil: { languages: ['fr'] },
    iedpc: { languages: ['en'] },
    nlap: { languages: ['en', 'nl'] },
    ptcnpd: { languages: ['pt'] },
};

export const dpas = Object.fromEntries(
    Object.entries(dpaData)
        .map(([k, v]) => [k, { ...v, ...dpaOverrides[k as 'lucnpd'] }] as const)
        .filter((d) => d[1]?.languages?.some((l) => supportedLanguages.includes(l as 'en'))),
);
